Test bash set (#2)
* Test bash set -e

* Test bash set -e

* Test bash set -e

* Test bash set -e

* Test bash set -e

* Test bash set -o pipefail

* Test bash set -o pipefail

* Finish test

* Remove topic branch from trigger

diff --git a/.github/workflows/bash-set.yml b/.github/workflows/bash-set.yml
--- a/.github/workflows/bash-set.yml
+++ b/.github/workflows/bash-set.yml
@@ -1,36 +1,30 @@
-# This is a basic workflow to help you get started with Actions
-
 name: Bash Set
 
-# Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the main branch
   push:
     branches: [main]
   pull_request:
     branches: [main]
-
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
+  test:
+    if: false
     runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v3
-
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: set -e
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          # no effect since GitHub Actions adds '/usr/bin/bash -e'
+          # should exit the script if any command returns a non-zero status
+          # without this, exit code will be 0 because of the last command
+          set -e
+          mkdir existing_folder
+          ls -l existing_folder
+          ls -l missing_folder
+          ls -l existing_folder
+      - name: set -o pipefail
+        run: |
+          # should exit the script if any pipe command returns a non-zero status
+          # without this, exit code will be 0 because of the last pipe command
+          set -o pipefail
+          mkdir existing_folder | ls -l existing_folder | ls -l missing_folder | ls -l existing_folder
